### ISSUE TITLE
Konsole

### ISSUE THREAD

**Issue by bretsky84** [seqizz/ulauncher-tmux-attach#1]
Does this extension offer support for Konsole in kde?  I tried just konsole in the terminal path as well as the path to the binary.

**Comment by seqizz** [comment]
There is no reason to not to support it. Please try these values on settings page:
Terminal: konsole
Attach parameters:  --new-tab -e 'tmux att -t %s'
New session parameters:  --new-tab -e 'tmux'

**Comment by bretsky84** [comment]
Works perfect, thank you!
